//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlManhal.TPS.Data.Model.POCOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStep
    {
        public int WorkflowStepID { get; set; }
        public int WorkflowID { get; set; }
        public int StepID { get; set; }
    }
}
