//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Resources.UI.ReviewThesis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Review {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Review() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWC.Resources.UI.ReviewThesis.Review", typeof(Review).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Details.
        /// </summary>
        public static string AuthorDetails {
            get {
                return ResourceManager.GetString("AuthorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Letter of approval of the Committee.
        /// </summary>
        public static string DownloadLetterApprovalOfCommittee {
            get {
                return ResourceManager.GetString("DownloadLetterApprovalOfCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Thesis File word (docx).
        /// </summary>
        public static string DownloadThesisFileDoc {
            get {
                return ResourceManager.GetString("DownloadThesisFileDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Thesis File PDF.
        /// </summary>
        public static string DownloadThesisFilePDF {
            get {
                return ResourceManager.GetString("DownloadThesisFilePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Details.
        /// </summary>
        public static string FacultyDetails {
            get {
                return ResourceManager.GetString("FacultyDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORG.
        /// </summary>
        public static string ORG {
            get {
                return ResourceManager.GetString("ORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending issue.
        /// </summary>
        public static string PendingIssue {
            get {
                return ResourceManager.GetString("PendingIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all required fields..
        /// </summary>
        public static string PleaseFillAllRequiredFields {
            get {
                return ResourceManager.GetString("PleaseFillAllRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the ORG..
        /// </summary>
        public static string PleaseFillORG {
            get {
                return ResourceManager.GetString("PleaseFillORG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the reason/s of rejecting..
        /// </summary>
        public static string PleaseFillReasonOfRejecting {
            get {
                return ResourceManager.GetString("PleaseFillReasonOfRejecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a status.
        /// </summary>
        public static string PleaseSelectResult {
            get {
                return ResourceManager.GetString("PleaseSelectResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reason/s of rejecting.
        /// </summary>
        public static string ReasonOfRejecting {
            get {
                return ResourceManager.GetString("ReasonOfRejecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis Abstracts.
        /// </summary>
        public static string ThesisAbstracts {
            get {
                return ResourceManager.GetString("ThesisAbstracts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis Details.
        /// </summary>
        public static string ThesisDetails {
            get {
                return ResourceManager.GetString("ThesisDetails", resourceCulture);
            }
        }
    }
}
