//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Resources.UI.SubmitThesis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThesisFormValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThesisFormValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWC.Resources.UI.SubmitThesis.ThesisFormValidation", typeof(ThesisFormValidation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Arabic Abstract&apos; field is required.
        /// </summary>
        public static string ArabicAbstract {
            get {
                return ResourceManager.GetString("ArabicAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Author Address&apos; field is required.
        /// </summary>
        public static string AuthorAddress {
            get {
                return ResourceManager.GetString("AuthorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Arabic Author Name&apos; field is required.
        /// </summary>
        public static string AuthorNameAr {
            get {
                return ResourceManager.GetString("AuthorNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;English Author Name&apos; field is required.
        /// </summary>
        public static string AuthorNameEn {
            get {
                return ResourceManager.GetString("AuthorNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Delegation of Scientific Papers&apos; field is required.
        /// </summary>
        public static string DelegationOfScientificPapers {
            get {
                return ResourceManager.GetString("DelegationOfScientificPapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Department Name&apos; field is required.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Email&apos; field is required.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;English Abstract&apos; field is required.
        /// </summary>
        public static string EnglishAbstract {
            get {
                return ResourceManager.GetString("EnglishAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Faculty Name&apos; field is required.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; accepts only ({1}) file format.
        /// </summary>
        public static string FileExtensions {
            get {
                return ResourceManager.GetString("FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;{0}&quot; File size must be less than or equal 100 MB.
        /// </summary>
        public static string FileSizeMaxMessage {
            get {
                return ResourceManager.GetString("FileSizeMaxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Graduation Date&apos; field is required.
        /// </summary>
        public static string GraduationDate {
            get {
                return ResourceManager.GetString("GraduationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Graduation Type&apos; field is required.
        /// </summary>
        public static string GraduationType {
            get {
                return ResourceManager.GetString("GraduationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string InvalidEmailAddress {
            get {
                return ResourceManager.GetString("InvalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Letter of approval of the Committee&apos; field is required.
        /// </summary>
        public static string LetterOfApprovalOfTheCommittee {
            get {
                return ResourceManager.GetString("LetterOfApprovalOfTheCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter no more than 10,000 characters..
        /// </summary>
        public static string maxlengthMessage {
            get {
                return ResourceManager.GetString("maxlengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Number of Pages&apos; field is required.
        /// </summary>
        public static string NumberOfPages {
            get {
                return ResourceManager.GetString("NumberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pages: Please enter a value greater than or equal to 1.
        /// </summary>
        public static string NumberOfPagesMinMessage {
            get {
                return ResourceManager.GetString("NumberOfPagesMinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Student ID&apos; field is required.
        /// </summary>
        public static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Subject&apos; field is required.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Supervisor Name&apos; field is required.
        /// </summary>
        public static string SupervisorName {
            get {
                return ResourceManager.GetString("SupervisorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Telephone&apos; field is required.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Thesis Language&apos; field is required.
        /// </summary>
        public static string ThesisLanguage {
            get {
                return ResourceManager.GetString("ThesisLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Arabic Thesis Title&apos; field is required.
        /// </summary>
        public static string ThesisTitleAr {
            get {
                return ResourceManager.GetString("ThesisTitleAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;English Thesis Title&apos; field is required.
        /// </summary>
        public static string ThesisTitleEn {
            get {
                return ResourceManager.GetString("ThesisTitleEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Thesis File word (docx)&apos; field is required.
        /// </summary>
        public static string UploadThesisFileDoc {
            get {
                return ResourceManager.GetString("UploadThesisFileDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The &apos;Thesis File PDF&apos; field is required.
        /// </summary>
        public static string UploadThesisFilePDF {
            get {
                return ResourceManager.GetString("UploadThesisFilePDF", resourceCulture);
            }
        }
    }
}
