//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Resources.UI.SubmitThesis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SubmitThesis {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SubmitThesis() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWC.Resources.UI.SubmitThesis.SubmitThesis", typeof(SubmitThesis).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Abstract.
        /// </summary>
        public static string ArabicAbstract {
            get {
                return ResourceManager.GetString("ArabicAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Address.
        /// </summary>
        public static string AuthorAddress {
            get {
                return ResourceManager.GetString("AuthorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Country.
        /// </summary>
        public static string AuthorCountry {
            get {
                return ResourceManager.GetString("AuthorCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill with author details.
        /// </summary>
        public static string AuthorInfoStepTitle {
            get {
                return ResourceManager.GetString("AuthorInfoStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author Name.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Author Name.
        /// </summary>
        public static string AuthorNameAR {
            get {
                return ResourceManager.GetString("AuthorNameAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Author Name.
        /// </summary>
        public static string AuthorNameEN {
            get {
                return ResourceManager.GetString("AuthorNameEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegation of Scientific Papers.
        /// </summary>
        public static string DelegationOfScientificPapers {
            get {
                return ResourceManager.GetString("DelegationOfScientificPapers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        public static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Abstract.
        /// </summary>
        public static string EnglishAbstract {
            get {
                return ResourceManager.GetString("EnglishAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty Name.
        /// </summary>
        public static string Faculty {
            get {
                return ResourceManager.GetString("Faculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill your faculty info.
        /// </summary>
        public static string FacultyInfoStepTitle {
            get {
                return ResourceManager.GetString("FacultyInfoStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 out of 5.
        /// </summary>
        public static string FifthStepTitleNo {
            get {
                return ResourceManager.GetString("FifthStepTitleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: File size must be less than or equal to 100 MB.
        /// </summary>
        public static string FileSizeNote {
            get {
                return ResourceManager.GetString("FileSizeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload the files.
        /// </summary>
        public static string FilesStepTitle {
            get {
                return ResourceManager.GetString("FilesStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The acceptable file format (docx, pdf).
        /// </summary>
        public static string FileTypeNote {
            get {
                return ResourceManager.GetString("FileTypeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the King Abdul Aziz University Publication Platform!
        ///The following wizard will take you through the needed steps to submit your thesis on our Platform..
        /// </summary>
        public static string FirstDescription {
            get {
                return ResourceManager.GetString("FirstDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 out of 5.
        /// </summary>
        public static string FirstStepTitleNo {
            get {
                return ResourceManager.GetString("FirstStepTitleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 out of 5.
        /// </summary>
        public static string FourthStepTitleNo {
            get {
                return ResourceManager.GetString("FourthStepTitleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Date.
        /// </summary>
        public static string GraduationDate {
            get {
                return ResourceManager.GetString("GraduationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Type.
        /// </summary>
        public static string GraduationType {
            get {
                return ResourceManager.GetString("GraduationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis Submission.
        /// </summary>
        public static string KAUHeaderSubTitle {
            get {
                return ResourceManager.GetString("KAUHeaderSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King Abdulaziz scientific platform.
        /// </summary>
        public static string KAUHeaderTitle {
            get {
                return ResourceManager.GetString("KAUHeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter of approval of the Committee.
        /// </summary>
        public static string LetterOfApprovalOfTheCommittee {
            get {
                return ResourceManager.GetString("LetterOfApprovalOfTheCommittee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My theses.
        /// </summary>
        public static string MyTheses {
            get {
                return ResourceManager.GetString("MyTheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pages.
        /// </summary>
        public static string NumberOfPages {
            get {
                return ResourceManager.GetString("NumberOfPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request successfully sent!.
        /// </summary>
        public static string RequestSuccessfullySent {
            get {
                return ResourceManager.GetString("RequestSuccessfullySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore ..
        /// </summary>
        public static string SecondDescription {
            get {
                return ResourceManager.GetString("SecondDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 out of 5.
        /// </summary>
        public static string SecondStepTitleNo {
            get {
                return ResourceManager.GetString("SecondStepTitleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Supervisor Name.
        /// </summary>
        public static string SecondSupervisorName {
            get {
                return ResourceManager.GetString("SecondSupervisorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student ID.
        /// </summary>
        public static string StudentID {
            get {
                return ResourceManager.GetString("StudentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit a new thesis.
        /// </summary>
        public static string SubmitNewThesis {
            get {
                return ResourceManager.GetString("SubmitNewThesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissertation and Thesis Submission.
        /// </summary>
        public static string SubmitThesisTitle {
            get {
                return ResourceManager.GetString("SubmitThesisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name.
        /// </summary>
        public static string SupervisorName {
            get {
                return ResourceManager.GetString("SupervisorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting your thesis to our platform.
        /// </summary>
        public static string ThankYouForYourTime {
            get {
                return ResourceManager.GetString("ThankYouForYourTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill with thesis Abstracts.
        /// </summary>
        public static string ThesisAbstractsStepTitle {
            get {
                return ResourceManager.GetString("ThesisAbstractsStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis file.
        /// </summary>
        public static string ThesisFile {
            get {
                return ResourceManager.GetString("ThesisFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis file word (docx).
        /// </summary>
        public static string ThesisFileDoc {
            get {
                return ResourceManager.GetString("ThesisFileDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis file PDF.
        /// </summary>
        public static string ThesisFilePDF {
            get {
                return ResourceManager.GetString("ThesisFilePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill with thesis info.
        /// </summary>
        public static string ThesisInfoStepTitle {
            get {
                return ResourceManager.GetString("ThesisInfoStepTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis Language.
        /// </summary>
        public static string ThesisLanguage {
            get {
                return ResourceManager.GetString("ThesisLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesis Title.
        /// </summary>
        public static string ThesisTitle {
            get {
                return ResourceManager.GetString("ThesisTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Thesis Title.
        /// </summary>
        public static string ThesisTitleAR {
            get {
                return ResourceManager.GetString("ThesisTitleAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Thesis Title.
        /// </summary>
        public static string ThesisTitleEN {
            get {
                return ResourceManager.GetString("ThesisTitleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 out of 5.
        /// </summary>
        public static string ThirdStepTitleNo {
            get {
                return ResourceManager.GetString("ThirdStepTitleNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session has been ended, please submit your thesis form again..
        /// </summary>
        public static string TokenTimeOutMessage {
            get {
                return ResourceManager.GetString("TokenTimeOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload thesis in word (docx) format.
        /// </summary>
        public static string UploadThesisFileDoc {
            get {
                return ResourceManager.GetString("UploadThesisFileDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload thesis in PDF format.
        /// </summary>
        public static string UploadThesisFilePDF {
            get {
                return ResourceManager.GetString("UploadThesisFilePDF", resourceCulture);
            }
        }
    }
}
