//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Resources.UI.KAUHtmlTemplate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PWC.Resources.UI.KAUHtmlTemplate.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        p.MsoNormal {
        ///            margin-bottom: .0001pt;
        ///            font-size: 11.0pt;
        ///            font-family: &quot;Calibri&quot;, &quot;sans-serif&quot;;
        ///            margin-left: 0cm;
        ///            margin-right: 0cm;
        ///            margin-top: 0cm;
        ///        }
        ///
        ///        p {
        ///            margin-right [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PendingIssueEmail {
            get {
                return ResourceManager.GetString("PendingIssueEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAUPP - Thesis is flipped to pending issue status.
        /// </summary>
        public static string PendingIssueEmailSubject {
            get {
                return ResourceManager.GetString("PendingIssueEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        p.MsoNormal {
        ///            margin-bottom: .0001pt;
        ///            font-size: 11.0pt;
        ///            font-family: &quot;Calibri&quot;, &quot;sans-serif&quot;;
        ///            margin-left: 0cm;
        ///            margin-right: 0cm;
        ///            margin-top: 0cm;
        ///        }
        ///
        ///        p {
        ///            margin-right [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RejectedThesisEmail {
            get {
                return ResourceManager.GetString("RejectedThesisEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAUPP - Thesis has been rejected.
        /// </summary>
        public static string RejectedThesisEmailSubject {
            get {
                return ResourceManager.GetString("RejectedThesisEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        p.MsoNormal {
        ///            margin-bottom: .0001pt;
        ///            font-size: 11.0pt;
        ///            font-family: &quot;Calibri&quot;, &quot;sans-serif&quot;;
        ///            margin-left: 0cm;
        ///            margin-right: 0cm;
        ///            margin-top: 0cm;
        ///        }
        ///
        ///        p {
        ///            margin-right [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SuccessPublishingThesisEmail {
            get {
                return ResourceManager.GetString("SuccessPublishingThesisEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAUPP - Thesis Approved and Puplished Online!.
        /// </summary>
        public static string SuccessPublishingThesisEmailSubject {
            get {
                return ResourceManager.GetString("SuccessPublishingThesisEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD XHTML 1.0 Transitional//EN&quot; &quot;http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd&quot;&gt;
        ///&lt;html xmlns=&quot;http://www.w3.org/1999/xhtml&quot;&gt;
        ///&lt;head&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot;&gt;
        ///        p.MsoNormal {
        ///            margin-bottom: .0001pt;
        ///            font-size: 11.0pt;
        ///            font-family: &quot;Calibri&quot;, &quot;sans-serif&quot;;
        ///            margin-left: 0cm;
        ///            margin-right: 0cm;
        ///            margin-top: 0cm;
        ///        }
        ///
        ///        p {
        ///            margin-right [rest of string was truncated]&quot;;.
        /// </summary>
        public static string SuccessSubmittingThesisEmail {
            get {
                return ResourceManager.GetString("SuccessSubmittingThesisEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KAUPP - Submitting a new thesis.
        /// </summary>
        public static string SuccessSubmittingThesisEmailSubject {
            get {
                return ResourceManager.GetString("SuccessSubmittingThesisEmailSubject", resourceCulture);
            }
        }
    }
}
