//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PWC.Data.Model.POCOs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaint
    {
        public int ComplaintID { get; set; }
        public int UserID { get; set; }
        public int StatusID { get; set; }
        public string Message { get; set; }
    
        public virtual ComplaintStatu ComplaintStatu { get; set; }
        public virtual User User { get; set; }
    }
}
